"use client";

/**
 * SAGE — Action Plan / Certification screen.
 * The calm, final, report-style output: a centered document column that
 * reads like a formal certification. No blueprint grid here — generous
 * whitespace, 1px borders, tonal layering, every number from the engine.
 * PDF export via jsPDF (single-page A4, text-only, guarded).
 */

import { useCallback, useEffect, useMemo, useState } from "react";
import { usePlant } from "@/lib/plant-store";
import { ProvenanceBadge } from "@/components/provenance-badge";
import { findBestPortfolio } from "@/lib/optimizer";
import { getAction } from "@/lib/action-catalog";
import { formatINR, formatNumber } from "@/lib/calc-engine";
import { jsPDF } from "jspdf";
import { APP_NAME, APP_TAGLINE } from "@/lib/brand";

/** Default portfolio budget — same as the landing page (₹45,00,000). */
const PORTFOLIO_BUDGET = 4500000;

/** ASCII-safe INR for the PDF (helvetica has no ₹ glyph). */
function pdfINR(value: number): string {
  return formatINR(value).replace("₹", "Rs. ");
}

/** Deterministic 4-digit doc suffix from the plant name — a certification
 *  number must be stable, so refreshing the page never changes it. */
function docSuffix(name: string): string {
  let h = 2166136261;
  for (let i = 0; i < name.length; i++) {
    h ^= name.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return String((h >>> 0) % 9000 + 1000);
}

export default function PlanPage() {
  const { input, footprint } = usePlant();

  // Budget portfolio — guarded so a bad input can never crash the page.
  const portfolio = useMemo(() => {
    try {
      return findBestPortfolio(input, PORTFOLIO_BUDGET, "cost-effective");
    } catch {
      return null;
    }
  }, [input]);

  // Report stamp + doc number — set once after mount (hydration-safe).
  const [stamp, setStamp] = useState({ date: "", time: "" });
  const [docNo, setDocNo] = useState("");

  useEffect(() => {
    const now = new Date();
    const stamp = {
      date: now.toLocaleDateString("en-GB", {
        day: "2-digit",
        month: "short",
        year: "numeric",
      }),
      time: now.toLocaleTimeString("en-GB", {
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit",
      }),
    };
    const key = `sage-plan-stamp-${input.name}`;
    try {
      const saved = localStorage.getItem(key);
      if (saved) {
        const parsed = JSON.parse(saved) as { date: string; time: string };
        setStamp(parsed);
        setDocNo(`DOC-${now.getFullYear()}-${docSuffix(input.name)}`);
        return;
      }
      localStorage.setItem(key, JSON.stringify(stamp));
    } catch {
      /* localStorage unavailable — fall through to in-memory stamp */
    }
    setStamp(stamp);
    setDocNo(`DOC-${now.getFullYear()}-${docSuffix(input.name)}`);
  }, [input.name]);

  const actions = portfolio?.actions ?? [];
  const capped = portfolio?.capped_reduction_tCO2e ?? 0;
  const pct =
    footprint.total_tCO2e > 0 ? (capped / footprint.total_tCO2e) * 100 : 0;

  /* ------------------------------------------------------------------ *
   * PDF export — single-page A4, text-only, never crashes.              *
   * ------------------------------------------------------------------ */
  const handleDownloadPdf = useCallback(() => {
    if (!portfolio) return;
    try {
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const M = 20;
      const W = doc.internal.pageSize.getWidth();
      const H = doc.internal.pageSize.getHeight();
      let y = M;

      // Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.text(`ACTION PLAN — ${input.name.toUpperCase()}`, M, y);
      y += 8;

      // Generated line
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(90);
      doc.text(
        `Generated by ${APP_NAME} · ${stamp.date} · Grade engine v1.0`,
        M,
        y,
      );
      y += 6;

      // Table header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(0);
      doc.text("SEQ", M, y);
      doc.text("INTERVENTION", M + 14, y);
      doc.text("REDUCTION", W - M - 42, y, { align: "right" });
      doc.text("COST", W - M, y, { align: "right" });
      y += 4;
      doc.line(M, y, W - M, y);
      y += 6;

      // Rows
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      portfolio.actions.forEach((a, i) => {
        doc.text(String(i + 1).padStart(2, "0"), M, y);
        doc.text(a.name, M + 14, y);
        doc.text(`-${formatNumber(a.reduction_tCO2e.value, 0)} tCO2e`, W - M - 42, y, {
          align: "right",
        });
        doc.text(pdfINR(a.cost_mid), W - M, y, { align: "right" });
        y += 6;
      });

      // Summary
      y += 4;
      doc.setFont("helvetica", "bold");
      doc.text(`TOTAL INVESTMENT: ${pdfINR(portfolio.total_investment)}`, M, y);
      doc.text(
        `TOTAL REDUCTION: -${formatNumber(portfolio.capped_reduction_tCO2e, 0)} tCO2e`,
        W - M,
        y,
        { align: "right" },
      );
      y += 6;
      doc.text(
        `PROJECTED GRADE: ${portfolio.current_grade} -> ${portfolio.projected_grade}`,
        M,
        y,
      );

      // Footer
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(`Generated by ${APP_NAME}`, M, H - 12);
      doc.text(docNo, W - M, H - 12, { align: "right" });

      const slug = input.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "");
      doc.save(`SAGE-action-plan-${slug}.pdf`);
    } catch {
      // PDF export must never crash the report screen.
    }
  }, [portfolio, input, stamp, docNo]);

  return (
    <div className="relative mx-auto flex max-w-[1280px] flex-col gap-8 px-4 py-6 md:px-8 md:py-10">
      {/* ============================================================ *
       * REPORT MASTHEAD                                               *
       * ============================================================ */}
      <section className="border border-line bg-surface p-6 md:p-8">
        {/* Eyebrow row */}
        <div className="flex items-center justify-between">
          <span className="label-caps text-[10px] text-ink-muted">
            Final Output Document
          </span>
          <button
            type="button"
            onClick={handleDownloadPdf}
            className="btn-press flex items-center gap-2 border border-line bg-accent px-4 py-2 text-accent-ink transition-colors hover:bg-accent/90"
          >
            <svg viewBox="0 0 16 16" className="h-4 w-4" fill="none" aria-hidden>
              <path
                d="M8 2v8M4.5 6.5 8 10l3.5-3.5"
                stroke="currentColor"
                strokeWidth="1.4"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path d="M3 12.5h10" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" />
            </svg>
            <span className="label-caps text-[10px] uppercase">Download PDF</span>
          </button>
        </div>

        {/* Title */}
        <h1 className="mt-3 font-display text-4xl font-bold uppercase leading-[0.95] tracking-tight">
          Action Plan — {input.name}
        </h1>

        {/* Sub-line */}
        <p className="mt-1 text-sm text-ink-muted">
          Generated by {APP_NAME} · {stamp.date || "—"} · Grade engine v1.0
        </p>

        {/* Stat blocks */}
        <div className="mt-6 grid grid-cols-2 gap-6 border-t border-line pt-5">
          <div className="border-l border-line pl-4">
            <div className="label-caps text-[10px] text-ink-muted">
              Projected CO2 Reduction
            </div>
            <div className="mt-1 font-display text-3xl font-bold leading-none text-accent">
              -{formatNumber(capped, 0)} tCO2e
            </div>
            <div className="mt-2 font-mono text-xs text-ink-muted">
              {formatNumber(pct, 1)}% of baseline
            </div>
          </div>
          <div className="border-l border-line pl-4">
            <div className="label-caps text-[10px] text-ink-muted">
              Certification Grade
            </div>
            <div className="mt-1 font-display text-3xl font-bold leading-none">
              {portfolio?.current_grade ?? "—"}{" "}
              <span className="text-ink-muted">→</span>{" "}
              {portfolio?.projected_grade ?? "—"}
            </div>
            <div className="mt-2 flex items-center gap-2">
              <ProvenanceBadge tag="scenario" />
              <span className="font-mono text-xs text-ink-muted">PROJECTED</span>
            </div>
          </div>
        </div>
      </section>

      {/* ============================================================ *
       * APPROVED INTERVENTIONS REGISTER                                *
       * ============================================================ */}
      <section className="border border-line bg-surface">
        {/* Panel header */}
        <div className="flex items-center justify-between border-b border-line px-6 py-4">
          <span className="label-caps text-sm">Approved Interventions Register</span>
          <span className="label-caps text-[10px] text-ink-muted">
            SEQ · {actions.length} INTERVENTIONS
          </span>
        </div>

        {/* Table header */}
        <div className="grid grid-cols-12 gap-4 border-b border-line px-6 py-3">
          <span className="label-caps col-span-1 text-[10px] text-ink-muted">SEQ</span>
          <span className="label-caps col-span-5 text-[10px] text-ink-muted">
            Intervention Protocol
          </span>
          <span className="label-caps col-span-3 text-[10px] text-ink-muted">
            Data Provenance
          </span>
          <span className="label-caps col-span-3 text-right text-[10px] text-ink-muted">
            Impact
          </span>
        </div>

        {/* Body rows */}
        {actions.map((action, i) => (
          <div
            key={action.action_id}
            className="grid grid-cols-12 items-center gap-4 border-b border-line px-6 py-3 last:border-b-0"
          >
            <span className="col-span-1 font-mono text-sm text-ink-muted">
              {String(i + 1).padStart(2, "0")}
            </span>
            <div className="col-span-5">
              <div className="font-display text-sm font-bold uppercase">
                {action.name}
              </div>
              <div className="label-caps mt-0.5 text-[10px] text-ink-muted">
                {action.difficulty} · {action.confidence} confidence
              </div>
            </div>
            <div className="col-span-3">
              <ProvenanceBadge tag={action.tag} />
              <div className="mt-1 font-mono text-[10px] text-ink-muted">
                {getAction(action.action_id).short_name}
              </div>
            </div>
            <div className="col-span-3 text-right">
              <div className="font-mono text-sm text-accent">
                -{formatNumber(action.reduction_tCO2e.value, 0)} tCO2e
              </div>
              <div className="mt-0.5 font-mono text-[10px] text-ink-muted">
                {formatINR(action.cost_mid)}
              </div>
            </div>
          </div>
        ))}

        {/* Footer band */}
        <div className="grid grid-cols-12 items-center gap-4 border-t border-line bg-bg-elevated px-6 py-4">
          <span className="label-caps col-span-8 text-[10px] text-ink-muted">
            Net Cumulative Impact
          </span>
          <div className="col-span-4 text-right">
            <div className="font-mono text-lg">-{formatNumber(capped, 0)} tCO2e</div>
            <div className="label-caps mt-0.5 text-[10px]">
              Total Investment {formatINR(portfolio?.total_investment ?? 0)}
            </div>
          </div>
        </div>
      </section>

      {/* ============================================================ *
       * DOCUMENT FOOTER                                               *
       * ============================================================ */}
      <footer className="mt-2 flex flex-col gap-4">
        {/* Row 1 */}
        <div className="grid grid-cols-2 gap-6">
          <div>
            <div className="label-caps text-[10px] text-ink-muted">Generated</div>
            <div className="mt-1 font-mono text-xs">
              {stamp.date ? `${stamp.date} · ${stamp.time}` : "—"}
            </div>
            <div className="label-caps mt-2 text-[10px] text-ink-muted">Validator</div>
            <div className="mt-1 font-mono text-xs">{APP_NAME} ENGINE v1.0</div>
          </div>
          <div className="flex items-center justify-center gap-2 border border-dashed border-line p-4">
            <svg viewBox="0 0 16 16" className="h-4 w-4" fill="none" aria-hidden>
              <path
                d="M2.5 13.5 4 9l6.5-6.5a1.8 1.8 0 0 1 2.5 0l.5.5a1.8 1.8 0 0 1 0 2.5L7 12l-4.5 1.5z"
                stroke="currentColor"
                strokeWidth="1.2"
                strokeLinejoin="round"
              />
              <path d="M9.5 3.5l3 3" stroke="currentColor" strokeWidth="1.2" />
            </svg>
            <span className="label-caps text-[10px] text-ink-muted">
              Digital Signature — Pending
            </span>
          </div>
        </div>

        {/* Row 2 */}
        <div className="flex items-center justify-between border-t border-line pt-3">
          <span className="label-caps text-[10px] text-ink-muted">Authorized Node</span>
          <span className="label-caps text-[10px] text-ink-muted">
            {APP_NAME} · {APP_TAGLINE}
          </span>
          <span className="font-mono text-[10px]">{docNo}</span>
        </div>
      </footer>
    </div>
  );
}